### ISSUE TITLE
cached path prefix weirness

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#100]
Here is the code for generating paths to files in cached locations

https://github.com/pangeo-forge/pangeo-forge/blob/ba4dc7430137ae854b358698f0eb84fb4232c032/pangeo_forge/storage.py#L82-L87

I thought that `prefix = hex(zlib.adler32(str(path).encode("utf8")))[2:10]` would always give a string of length 8, but apparently this is not the case.

We should use something more robust here.

**Comment by martindurant** [comment]
`uuid.uuid4().hex`[:8] ?

**Comment by rabernat** [comment]
But I don't want a uuid, I want a hash of the original url path.

**Comment by martindurant** [comment]
Ah. `hashlib.md5(path.encode()).hexdigest()`
