### ISSUE TITLE
prepare_target is triggering distributed client calls

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#112]
This is a very hard issue to reproduce / document simply, but the basic problem is simple to describe. All of individual tasks within a recipe  should just execute in simple single-threaded mode, even if there is an active dask client present. I can tell that this is not happening correctly when I manually call `recipe.prepare_target()` from a notebook session with an active dask client. I can see xarray tasks running on the client.

**Comment by cisaacstern** [comment]
Closing as not relevant post-`0.10.0`.
