### ISSUE TITLE
Issue on page /tutorials/cmip6-recipe.html

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#115]
This recipe needs to be rewritten with the new FilePattern and XarrayZarrRecipe syntax. Should not be hard.

**Comment by rabernat** [comment]
The notebook in question is here: https://github.com/pangeo-forge/pangeo-forge/blob/master/docs/tutorials/cmip6-recipe.ipynb.

@cisaacstern - this could be another good issue to take on to spin yourself up on pangeo forge usage from a user perspective.

**Comment by cisaacstern** [comment]
@rabernat, this looks like a great next step for me. will look at this as soon as I've submitted the renaming PR.
