### ISSUE TITLE
Factor sphinx theme into a standalone template

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#126]
The sphinx theme used here is a customized version of the Sphinx Book Theme. I think it looks much better than our old pangeo sphinx theme. 

We should factor it out into a standalone template that we can use for other sites (like we did for our earlier theme: https://github.com/pangeo-data/sphinx_pangeo_theme). That would help with other projects (e.g. https://github.com/pangeo-data/pangeo/issues/835).

**Comment by cisaacstern** [comment]
I created a new repo, [pangeo-forge/pangeo-sphinx-book-theme](https://github.com/pangeo-data/sphinx_pangeo_theme), as a place to work on this.

The earlier theme repo puts the name `sphinx` ahead of `pangeo`; I've reversed this order in hopes of avoiding name confusion between these two themes.

I'm not sure if there was a (sphinx-specific?) reason why underscore delimiters were used in the name of the prior repo, but I've gone with the more generic dash delimiters for now.
