### ISSUE TITLE
Usage question: how to use pangeo-forge recipes as a user

### ISSUE THREAD

**Issue by aaronspring** [pangeo-forge/pangeo-forge-recipes#152]
I have a user question (not sure whether it fits here well)

Should I as a user run a recipe on my local machine? I guess some but couldn’t find a section in the docs when skimming over.

 Or will it be as in conda-forge that I can easily download a compiled, here nicely chunked zarr, from some server? Like

pangeo get recipename
pangeo get NOAA-OISSTv4.2_some_more_details

Sounds similar to the bakery?

**Comment by rabernat** [comment]
Thanks for your question Aaron. I agree that this is not well documented currently. We are currently lacking a good "high level" documentation of the Pangeo Forge project. This [Roadmap](https://github.com/pangeo-forge/roadmap) will have to suffice for now.

We try to address your question a bit in the [bakeries page](https://pangeo-forge.readthedocs.io/en/latest/bakeries.html)

> As described in Recipe Execution, you can define and execute recipes on your own computers using the executor of your choice. However, you can also contribute your recipe to the Pangeo Forge The Recipe Box. and have it executed automatically in the cloud. Cloud based execution is provided by Bakeries.

> Or will it be as in conda-forge that I can easily download a compiled, here nicely chunked zarr, from some server?

We will not provide a "download" feature; the point of the bakeries is to populate cloud-native data repositories which are accessible to data-proximate computing, or just lazy loading over the internet.

**Comment by aaronspring** [comment]
recipe.to_function() .to_dask() etc
