### ISSUE TITLE
Help understanding if data is being repeatedly written

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-forge/pangeo-forge-recipes#159]
I'm wondering if we're repeatedly writing the data for every variable in a Dataset that's indexed by the concat dim, that don't happen to be the "primary" variable in the NetCDF dataset.

Say I have a recipe where the source files are a bunch of NetCDF, one per variable / time step. In my case I have "primary" variables (`tmin`, `tmax`) with dimensions `(time, y, x)`. I say "primary" since there are some other variables like `yearday` and `time_bnds` that are also indexed by time and are in the file.

In pangeo-forge, that's something like this:

```python
def make_format_function(region, frequency):
    template = "https://daymeteuwest.blob.core.windows.net/daymet-nc/daymet_v4_{frequency}/daymet_v4_daily_{region}_{{variable}}_{{time}}.nc".format(region=region, frequency=frequency)
    def format_function(variable, time):
        if variable == "prcp":
            kind = "ttl"
        else:
            kind = "avg"
        return template.format(variable=variable, kind=kind, time=time)
    return format_function


    variable_merge_dim = patterns.MergeDim("variable", keys=["tmin", "max"])
    time_concat_dim = patterns.ConcatDim("time", keys=list(range(1980, 2021)), nitems_per_file=365)
    pattern = patterns.FilePattern(make_format_function("na", "daily"), variable_merge_dim, time_concat_dim)

    recipe = XarrayZarrRecipe(
        pattern,
        cache_inputs=False,
        copy_input_to_local_file=True
    )
```

AFAICT, in https://github.com/pangeo-forge/pangeo-forge-recipes/blob/d96c57ca8a286fa3504b385f344cf4a63a350eca/pangeo_forge_recipes/recipes/xarray_zarr.py#L308 we loop over all the we loop over the variables in that chunk that are indexed by `time`. In my test case, that's `[time, yearday, time_bnds, tmax]` when working with the `tmax` variable, and `[time, yearday, time_bnds, tmin]` when working with `tmin`.

For each of those variables, we eventually write the data: https://github.com/pangeo-forge/pangeo-forge-recipes/blob/d96c57ca8a286fa3504b385f344cf4a63a350eca/pangeo_forge_recipes/recipes/xarray_zarr.py#L332.

Does that mean we write the data for things like `time` (and other variables indexed by `time`) twice, once for `tmin` and once for `tmax`?

---

I'm working with the daymet dataset. When I did this manually, I picked a special variable to also write all these expanding variables. So `tmax` would write `tmax`, `time`, `yearday`, and `time_bnds`. When writing `tmin` I would just write `tmin`.
 
If my understanding is correct, we could look at `chunk_key` and only write these expanding variables if some condition is met. Something like

```python
if chunk_key[0] != 0:
    to_drop.extend(["time", "yearday", "time_bnds"]) # find the additional variables rather than hard-coding.
```

I don't think we can rely on that chunking pattern though.

**Comment by rabernat** [comment]
The is an important distinction between the "variable" concept in the file pattern and the variables inside the netcdf / Zarr files. I think you understand this. Let's call these _filename variables_ and _internal variables_. 

> Does that mean we write the data for things like `time` (and other variables indexed by `time`) twice, once for `tmin` and once for `tmax`?

Yes, I think this is the correct interpretation. Any _internal variables_ that appears in multiple _filename variables_ will be written multiple times. Usually this is just small coordinates like time, etc., so not very expensive and thus (IMO) not a major issue. Could you say more about why this is a problem for you? Yes it's a bit redundant, but the dataset is not wrong. Is the locking slowing things down significantly?

In theory, this could perhaps be handled at the user level with a `process_chunk` function.

Alternatively, we could use the metadata cache (a manifest of each file's contents) to identify duplicate variables across the merge dim.

**Comment by rabernat** [comment]
More specifically, here
https://github.com/pangeo-forge/pangeo-forge-recipes/blob/d96c57ca8a286fa3504b385f344cf4a63a350eca/pangeo_forge_recipes/recipes/xarray_zarr.py#L277-L278

we could optionally add a `duplicate_variables` key to `recipe_meta` with the values of the variables that match this scenario (e.g. `['time', 'yearday', 'time_bnds']`). This list could be determined in a similar way that we determine the input sequence lens, i.e.

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/d96c57ca8a286fa3504b385f344cf4a63a350eca/pangeo_forge_recipes/recipes/xarray_zarr.py#L493-L496

by examining the input metadata, we could determine which variables match this criteria for duplication.

**Comment by TomAugspurger** [comment]
Thanks.

> Usually this is just small coordinates like time, etc., so not very expensive and thus (IMO) not a major issue. Could you say more about why this is a problem for you? Yes it's a bit redundant, but the final dataset is not wrong. Is the locking slowing things down significantly?

Correct, these are small variables, and shouldn't have a large effect on the runtime of the entire job. I was primarily interested in why there was any locking necessary in my recipe, and these shared "internal" variables looked like a potential culprit. When the deadlock issue is fixed, this duplicate writing won't be too bad of an issue.

**Comment by TomAugspurger** [comment]
Closing, since I don't think there's an action item here.
