### ISSUE TITLE
Support Beam as an executor for recipe pipelines

### ISSUE THREAD

**Issue by alxmrs** [pangeo-forge/pangeo-forge-recipes#169]
As discussed in today's [meeting], our internal users would really like to execute Recipes on [Beam] (and Dataflow). What is the best way to support this functionality? 

To this end, I mentioned using [XArray-Beam] within Pangeo in the meeting. @rabernat pointed out that this is probably not the best direction, since we don't necessarily want to introduce a dependency on that project.

[meeting]: https://docs.google.com/document/d/14FpI9vaM6TeFtmM7LP9o_d5DZaYKgQVTTzT7tFRt-Nw/edit#heading=h.u9p2mwlg964t
[Beam]: https://beam.apache.org/
[XArray-Beam]: https://github.com/google/xarray-beam

**Comment by rabernat** [comment]
> To this end, I mentioned using [XArray-Beam](https://github.com/google/xarray-beam) within Pangeo in the meeting. @rabernat pointed out that this is probably not the best direction, since we don't necessarily want to introduce a dependency on that project.

It's not so much that we don't want the dependency. It's more that XArray-Beam contains higher-level abstractions that we are not able to take advantage of inside pangeo_forge_recipes. The execution model is extremely simple, as you can see from the simple serial functional executor:

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/6fb5a0a9ae45e26577c8a55d33737f41008b6b19/pangeo_forge_recipes/recipes/base.py#L97-L111

The prefect executor is not much more complicated. The only difference is that it can parallelize certain stages (`map` over a sequence of inputs or chunks).

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/6fb5a0a9ae45e26577c8a55d33737f41008b6b19/pangeo_forge_recipes/recipes/base.py#L156-L175

The details of what is happening inside those functions are completely hidden to the executor. The execution knows nothing about Xarray, and indeed, we will eventually have recipe classes that don't use Xarray at all.

For a Beam executor, you would just want to replicate this pattern with a `to_beam()` method, which returns a `beam.PTransform` for the recipe. The Beam executor for rechunker would be a reasonable template to start with.

cc @shoyer

**Comment by alxmrs** [comment]
> It's more that XArray-Beam contains higher-level abstractions ... The execution knows nothing about Xarray, and indeed, we will eventually have recipe classes that don't use Xarray at all.

That makes total sense to me. Thank you for the examples. 

If no one else is slated to work on this I'm happy to take it on, especially with help from yourself and the community.

**Comment by alxmrs** [comment]
As a starting point, I am working on a PR in Rechunker to extend the `ParallelPipelines` model to the Beam executor (guided by https://github.com/pangeo-data/rechunker/pull/77). How does this sound? If I understand well how the projects are interrelated, this should make implementing `to_beam()` straightforward.

**Comment by rabernat** [comment]
> How does this sound?

We need to think about this a little bit. As part of a quest to make the executors more efficient, we have been considering deprecating the rechunker / pipelines dependency and directly implementing the execution within the `pangeo_forge_recipes.recipes.Base` class. But I'm no longer sure that was a necessary step.

I would be very curious to hear @TomAugspurger's opinion on whether that is still needed after the refactor in #160. Specifically, is there any significant difference between the graph produced by

```python
delayed = recipe.to_dask()
```

vs

```python
pipelines = recipe.to_pipelines()
from rechunker.executors import DaskPipelineExecutor 
executor = DaskPipelineExecutor(pipelines)
delayed = executor.pipelines_to_plan(pipelines)
```

???

**Comment by TomAugspurger** [comment]
We'll want to separate the API design discussion from the implementation discussion. API-wise, I think it's nice for users to have a `.to_<executor>`. Ideally, that would be implemented as `<Executor>.pipelines_to_plan(self.to_pipelines()).compute()`.

#160 primarily dropped the detour through `pipelines_to_plan()` to expedite the implementation. I think that with a bit of effort, possibly involving PRs to both pangeo-forge-recipes and rechunker. Actually, glancing at the final implementation, it's possible that the Dask graph generated by `DaskExecutor.pipelines_to_plan(recipe.to_pipelines())` will be (essentially) equivalent to the output of `recipe.to_dask()`.

**Comment by alxmrs** [comment]
I've been chipping away at this issue today, this time implementing `to_beam()` in Rechunker (in offline discussion IIRC, this was the recommended way to proceed). 

I have an explanation as to why any approach that allows side effects in function closures (which includes the current `MultiStagePipeline` model in rechunker) won't work for Beam executors. 

Here is a naive implementation of a beam executor in rechunker that uses multi-stage pipelines: https://github.com/alxmrs/rechunker/commit/e0361315787d632af1e8f6f59d289e0d28337ed9

The Beam executor fails the test suite with the following error: 

```
>   lambda x: dumps(x, protocol), pickle.loads)
E   AttributeError: Can't pickle local object 'example_pipeline.<locals>.func0'
```

Digging a bit deeper – the states of each stage in the tests are fundamentally unpicklable (see [these docs](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled)). Beam requires serialization in order to fan out both transformations and collections. 

I think we need a new structure if we want to support pangeo-forge execution on Apache Beam. 

A naive idea I've started to explore (https://github.com/alxmrs/rechunker/commit/129f4cd2c78056bc738f31d9752f81be4666ea47) includes creating a "stateful" type of multi-stage pipeline, where recipe writes can include a shared context for each stage.

**Comment by alxmrs** [comment]
Further serialization discussion in #211
