### ISSUE TITLE
Codecov statuses don't appear on PRs

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#172]
Our tests generate coverage reports and upload them to codecov

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/b9f74be590a25d1e013cfd03a834ab134c028411/.github/workflows/main.yaml#L56-L63

We have a `codecov.yml` file

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/b9f74be590a25d1e013cfd03a834ab134c028411/codecov.yml#L1-L21

And we have an active public page on codecov: https://app.codecov.io/gh/pangeo-forge/pangeo-forge-recipes

However, codecov is not providing coverage reports on PRs, which is a very important feature.

_Can anyone figure out why not and fix it?_

**Comment by cisaacstern** [comment]
@rabernat, the problem may be that we don't have the Codecov app installed in `pangeo-forge-recipes`?

https://docs.codecov.com/docs/error-reference#no-statuses-or-pull-requests-are-posting suggests that **No statuses** may relate to Team Bot authentication. But when you click through to the [Team Bot docs](https://docs.codecov.com/docs/team-bot), they suggest installing the Codecov Github App.  And here's a comment which lends a bit more support to this solution: https://github.com/spack/spack/issues/6173#issuecomment-346535040

I've made a request to install the app, but seems like I don't have permission to approve the request:

<img width="300" alt="Screen Shot 2021-08-27 at 4 37 49 PM" src="https://user-images.githubusercontent.com/62192187/131200669-4d8d75f6-253a-45a7-b387-968062cea39f.png">

If you go to https://github.com/apps/codecov or https://github.com/apps/codecov/installations/new, are you able to approve this install?

**Comment by rabernat** [comment]
Nice idea! That sounds like the likely cause. I just installed it, let's see what happens.

**Comment by cisaacstern** [comment]
https://github.com/pangeo-forge/pangeo-forge-recipes/pull/167

<img width="954" alt="Screen Shot 2021-08-30 at 10 59 32 AM" src="https://user-images.githubusercontent.com/62192187/131383894-2e6686ff-3009-4d88-b2c8-127586220ad0.png">
