### ISSUE TITLE
Create new release.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-recipes#180]
We need an updated release to support the use of `subset_inputs` in our CI actions ref https://github.com/pangeo-forge/staged-recipes/pull/68#issuecomment-896243447.

**Comment by cisaacstern** [comment]
I'll defer to @rabernat on this one, as I haven't made a release yet and not sure of the protocol. I see the Release Notes have already been updated: https://pangeo-forge.readthedocs.io/en/latest/development/release_notes.html#unreleased. Ryan, what are the next steps?

**Comment by rabernat** [comment]
The process is just to go to https://github.com/pangeo-forge/pangeo-forge-recipes/releases/new and create the 0.5.0 release. GitHub actions will do the rest. I'll do it right now, but anyone else should feel free to do it in the future.
