### ISSUE TITLE
Benchmarking large file opening/subsetting using various methods

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#183]
At the 2021-08-16 Pangeo Forge Coordination Meeting ([minutes](https://docs.google.com/document/d/14FpI9vaM6TeFtmM7LP9o_d5DZaYKgQVTTzT7tFRt-Nw/edit)), we discussed benchmarking large file opening/subsetting using various methods, including:

- `xarray.open_dataset` (current baseline)
- Calling `h5py` directly
- `fsspec-reference-maker`

One set of "problem" files I can recommend for this task are the inputs for https://github.com/pangeo-forge/staged-recipes/pull/56, cached here:

```python
import gcsfs

fs_gcs = gcsfs.GCSFileSystem(anon=True)
cache_base = "pangeo-forge-us-central1/pangeo-forge-cache"
recipe = "cesm_pop_lowres_1deg/v5_rel04_BC5_ne30_g16"
fs_gcs.ls(f"{cache_base}/{recipe}")
```
Each of these 14 netCDF files contain a single variable array spanning > 60,000 time steps, occupying 15-20 GB on disk, and approaching 30 GB in-memory. Anecdotally, they require 4-9 minutes each to open with `xr.open_dataset` (running from a same-region/same-provider Pangeo notebook). To bring subsets of these arrays into the sub-500 MB range for writing with `store_chunk`, 60 subsets are required. Using our `subset_inputs` feature (which calls `xr.open_dataset` on each subset), that means running a full recipe would require
```
14 files  x  60 subsets  x  5 mins  =  70 hours
```
in file-opening time.

It's important to note that it is precisely the repetitive file-opening of *subsetting* which creates such an egregious time sink (5 minutes for opening a file isn't so bad, if it only has to happen once or twice). As such, the benchmarking will have to include an assessment of subsetting efficiency, not just single-time opening. (In the case of `fsspec-reference-maker`, e.g., the first file-opening may be of comparable speed to `xr.open_dataset`, but subsequent subsetting is likely to be considerably faster.)

I will take the lead on this benchmarking and follow-up here with findings as they come together.

**Comment by rabernat** [comment]
I highly recommend using some profiling on `xr.open_dataset` to learn about what is taking so much time. [Snakeviz](https://jiffyclub.github.io/snakeviz/) works great here.

We could be generating the reference file system as an optional step inside `cache_input_metadata`.

**Comment by cisaacstern** [comment]
Here's a page with links to a few Snakeviz renders:

https://cisaacstern.github.io/netcdf-opening-profiles/

I've started off with one of the "problematic" CESM-POP inputs referenced in https://github.com/pangeo-forge/pangeo-forge-recipes/issues/183#issue-973283045 alongside one of the inputs for https://github.com/pangeo-forge/staged-recipes/pull/24, which is roughly the same size in-memory, but opens ~100x faster.

**Comment by cisaacstern** [comment]
I posted about this on Twitter some weeks ago, and just received [a response](https://twitter.com/edhartnett/status/1435734747305680901?s=20) from @edwardhartnett with a link to https://www.researchgate.net/publication/330346883_NetCDF-4_Performance_Improvements_Opening_Complex_Data_Files, which may be of use in our further consideration of this topic. Thanks for that link, Edward!

**Comment by cisaacstern** [comment]
Perhaps this issue will resurface, but I have not heard concern about it lately (last comment here was 2 years ago), so closing this.
