### ISSUE TITLE
conda forge recipe

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#197]
We should create a conda forge recipe for pangeo forge.

**Comment by cisaacstern** [comment]
I'm very curious to see how that works, as I've never made one before, and I'm sure the process will be super informative for the design of our contribution process.

**Comment by rabernat** [comment]
Then go for it! Docs should be self-explanatory, but ping me if you get stuck.

**Comment by jrbourbeau** [comment]
Just noting that `fsspec-reference-maker` is now on conda-forge https://anaconda.org/conda-forge/fsspec-reference-maker

**Comment by cisaacstern** [comment]
Great, thanks!

**Comment by cisaacstern** [comment]
PR opened: https://github.com/conda-forge/staged-recipes/pull/16146#issuecomment-917472984

In [local testing](https://conda-forge.org/docs/maintainer/adding_pkgs.html#staging-test-locally), conda flagged that `prefect 0.15.5` needed a specific version range of `requests`: https://github.com/cisaacstern/staged-recipes-1/commit/36525b798b2cca5572b294ef7bc6c2fdd60b12ce. I wonder why this hasn't come up in our CI workflows?

>  - [ ] GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

And @rabernat, for the sake of completeness, do you confirm that you are willing to be listed as a maintainer?

**Comment by cisaacstern** [comment]
https://github.com/conda-forge/pangeo-forge-recipes-feedstock has existed for a while, I just forgot to close this!
