### ISSUE TITLE
copy_pruned subset_inputs potential incompatibility.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-recipes#200]
While performing some further testing on HDF garbage collection related issues on https://github.com/pangeo-forge/staged-recipes/pull/68 I have discovered a potential issue with recipes which employ `subset_inputs`.  When using https://github.com/pangeo-forge/pangeo-forge-recipes/pull/139 to run reduced dimension versions of our recipes in CI testing we can encounter the case where our reduced dimension set will fail the sequence length [sanity check ](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/master/pangeo_forge_recipes/utils.py#L33).  I'm not sure of the best structural approach to alleviate this issue but I'd be happy to collaborate on a PR.  This will most likely affect CI testing for all recipes that employ https://github.com/pangeo-forge/pangeo-forge-recipes/pull/166

**Comment by rabernat** [comment]
Thanks @sharkinsspatial for the issue. Would it be possible to provide a MRE?

**Comment by sharkinsspatial** [comment]
Most definitely, I will try to post one tomorrow. 👍

**Comment by rabernat** [comment]
Hi @sharkinsspatial - just a ping to try to turn this into a MRE so we can get to the bottom of it. If that's not feasible, a debug log and stack trace from a real-world run would be helpful.
