### ISSUE TITLE
Expose recipe functions as public API

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#223]
The big refactor in #219 was purely internal, but I propose that we also make it part of the public API.

Currently, if a user wants to manually execute a recipe, they do it like this:
```python
recipe = XarrayZarrRecipe(**kwargs)
for input_key in recipe.iter_inputs():
    recipe.cache_input(input_key)
recipe.prepare_target()
# etc
```

However, those methods now only exist for backwards compatibility. It would be much simpler to recommend that the user just do
```
from pangeo_forge_recipes.recipes.xarray_zarr import iter_inputs, cache_input, prepare_target
recipe = XarrayZarrRecipe(**kwargs)
for input_key in iter_inputs(config=recipe):
    cache_input(input_key, config=recipe)
prepare_target(config=recipe)
# etc.
```

This would be easier to maintain. What do people think? Is there a better API possible?

To make this work, we would need to:

- [ ] Clarify which functions in the recipe modules are public vs private
- [ ] Provide good doc strings for all public functions
- [ ] Update narrative documentation to be consistent
- [ ] Update tutorials to be consistent

Also note that this goes very well a refactor of the tests towards more unit testing (#173).

**Comment by cisaacstern** [comment]
These functions are all superseded by `0.10.0`, so closing.
