### ISSUE TITLE
Use more granular stages for XarrayZarrRecipe

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#224]
Here is the current "compiler" for the XarrayZarrRecipe

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/0abcaa2438f7ba5966cc49a55f72470d551bec70/pangeo_forge_recipes/recipes/xarray_zarr.py#L586-L593

After #219, we are no longer bound to follow this same exact sequence for every recipe. We could imagine breaking things up instead like

```
     stages = [ 
         Stage(name="cache_input", function=cache_input, mappable=list(recipe.iter_inputs())), 
         Stage(name="cache_metadata", function=cache_metadata, mappable=list(recipe.iter_inputs())), 
         Stage(name="make_fsspec_reference", function=make_fsspec_reference, mappable=list(recipe.iter_inputs())), 
         Stage(name="prepare_target", function=prepare_target), 
         Stage(name="store_chunk", function=store_chunk, mappable=list(recipe.iter_chunks())), 
         Stage(name="finalize_target", function=finalize_target), 
     ] 
```

i.e. adding explicit stages for metadata caching and reference making. We could also add some conditional logic to this compiler to skip certain stages if they are not needed.

**Comment by jbusecke** [comment]
@rabernat I just wanted to point out that #355 might be a relevant use case for more granular stages as proposed here.

**Comment by cisaacstern** [comment]
The modularity of the Apache Beam refactor solves the issues discussed here! 🎉 So closing.
