### ISSUE TITLE
Missing BlockSizeError in fsspec 2021.11.1 breaks pangeo-forge-recipes import

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#246]
The HTTP `BlockSizeError` was [removed in fsspec 2021.11.1](https://github.com/fsspec/filesystem_spec/commit/2de1b53646b23d989902017e916c5a57397895a8). This breaks pangeo-forge-recipes because we import that error here

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/6b44109c663eae2d494afa54c56d127dc33a6058/pangeo_forge_recipes/storage.py#L16

The short term workaround is to run pangeo-forge-recipes with `fsspec==2021.11.0`.

@martindurant, how would we replicate this error handling

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/6b44109c663eae2d494afa54c56d127dc33a6058/pangeo_forge_recipes/storage.py#L41-L47

with the latest fsspec release? Your message on the above-linked `Remove BlockSizeError` commit reads 

> Does *not* allow random access from not the start of the download

so I think we still need this type of error handling?

**Comment by martindurant** [comment]
You ought not to need that any more, files read start-to-finish like this (without random access) should just work
