### ISSUE TITLE
Improve debuggability of "Inconsistent sequence lengths" error message.

### ISSUE THREAD

**Issue by alxmrs** [pangeo-forge/pangeo-forge-recipes#253]
I'm running the XarrayZarrRecipe on a large Grib dataset (Era 5). My FilePattern is structured as follows: 

```
    # ...
    def make_path(time: datetime.datetime, chunk: str) -> str:
        """Make path to Era5 data from timestamp and variable."""

        return (
            f"gs://some/gcs/bucket/"
            f"{time.year:04d}/{time.year:04d}{time.month:02d}_hres_{chunk}.grb2"
        )

    date_range = [
        ts.to_pydatetime()
        for ts in pd.date_range(start=parsed_args.start,
                                end=parsed_args.end,
                                freq="MS").to_list()
    ]
    date_dim = ConcatDim("time", date_range)
    chunks_dim = MergeDim("chunk", parsed_args.chunks)
    pattern = FilePattern(make_path, date_dim, chunks_dim)

    # ...
```

To summarize how the data is structured: Each file is contains a "chunk" of several related variables for a single month.

As I execute the Recipe, I eventually hit this error message in the `prepare_target` stage:

```
ValueError: Inconsistent sequence lengths found: f[[744 744 744 ... 744 744 744]
 [672 672 672 ... 672 672 672]
 [744 744 744 ... 744 744 744]
 ...
 [744 744 744 ... 744 744 744]
 [720 720 720 ... 720 720 720]
 [744 744 744 ... 744 744 744]]
```

After talking with @cisaacstern, the suspected root cause of the error is that some value is inconsistent from the rest of the row that it belongs. In other words, one of the files (or, associated metadata cache) has the wrong number of timesteps compared to all the other merge dimension chunks on that year x month. 

I mention this background context to motivate the need for a better error message here: To fix the Zarr conversion of my pipeline, I need to know: 
- If all the data is really there (for every row, is there one or more value that's different from all the other rows?)
- If it's not there, which item in the concat dimension is missing (what rows have problems?)
- What particular files from the file-pattern path are the culprit?
- Is this really a data error? Or, was the metadata cache produced erroneously? 

Ideally, the error message could be improved to help me answer some or all of these questions.

**Comment by rabernat** [comment]
Here is the relevant code block

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/4f8c0522c1395aaf15a820cfd637a1f1e76729b2/pangeo_forge_recipes/recipes/xarray_zarr.py#L393-L400

Basically, this check only comes into play when there is both a merge dim and a concat dim. The error is showing that some of the variables across the merge dim have different lengths in the concat dim. This means that the data can't actually be combined consistently using a single concat dim coordinate. In general, if they data have different time coordinates, they can't be combined into a single dataset; we would need multiple recipes.

**Comment by rabernat** [comment]
I suppose there could be a situation that we have not planned for, in which a _single file_ contains _multiple time coordinates_. For example: if the same file contains both hourly and daily data. Then we would need to figure out how to handle this case of two xarray dimensions along the same concat axis. But I don't think that's what is happening here.

**Comment by martindurant** [comment]
> in which a single file contains multiple time coordinates

I certainly saw gribs where there were multiple vertical height coordinate systems: some variables defined at particular heights, others at a range of other values. These cannot be combined into the same Z coordinate, but you could build a dataset with multiple independent Zs.

**Comment by rabernat** [comment]
Multiple coordinates orthogonal to the time dimension (or whatever the concat dim is) should be fine.
