### ISSUE TITLE
Double rendering of title on sphinx website

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#262]
https://pangeo-forge.readthedocs.io/en/latest/

Title appears twice and "contents" appear at the top of the page.

![image](https://user-images.githubusercontent.com/1197350/149969950-42fd5edd-c375-4620-b626-5312eaf99a02.png)

Also noted in https://github.com/pangeo-forge/pangeo-forge-orchestrator/pull/28

I wonder if this is an upstream issue. The dependency chain is

- https://github.com/pangeo-forge/pangeo-sphinx-book-theme
- https://github.com/executablebooks/sphinx-book-theme

My hunch is that this is related to the release of sphinx_book_theme [0.2.0](https://github.com/executablebooks/sphinx-book-theme/releases/tag/v0.2.0)

**Comment by cisaacstern** [comment]
Looks like this issue was solved, closing.
