### ISSUE TITLE
Bumping documentation

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-forge/pangeo-forge-recipes#28]
With the major refactor to pangeo-forge pending, it would be timely to update the documentation to adequately represent the direction it is going in. This should include:

- Definition of what Executors, Pipelines, and Recipes are
  - Basic functionality of Recipes such as `prepare()`, `cache_input()`, `store_chunk()`, ...
- Tutorials on how to make and submit a recipe
- Information on how to extend pangeo-forge with new Recipe classes

It might be useful to consider what info we consider more fitting for the landing page [as we begin to populate that](pangeo-forge/pangeo-forge.org#31). Since the docs are published through [Read The Docs](https://readthedocs.org/projects/pangeo-forge/), I think we should probably add some additional maintainers to our project there, since currently the only one is @TomAugspurger.

**Comment by TomAugspurger** [comment]
Happy to add others there, if you could post your RTD username.

**Comment by charlesbluca** [comment]
Sure, my username is same as here - charlesbluca.

**Comment by TomAugspurger** [comment]
Invite sent.

**Comment by charlesbluca** [comment]
Thanks! I'll let you know if I have any other questions about the settings on RTD.

**Comment by charlesbluca** [comment]
As part of this process, I have added a [simple workflow](https://github.com/pangeo-forge/pangeo-forge/blob/master/.github/workflows/preview.yml) to generate previews of the documentation in response to PRs.

Since this workflow creates new (preview) branches whenever a local PR is made affecting `docs/`, I would also like to modify [`main.yaml`](https://github.com/pangeo-forge/pangeo-forge/blob/master/.github/workflows/main.yaml) so that only `push`es to the `master` branch will trigger CI, as currently it would also be running unnecessarily on preview branches.

**Comment by rabernat** [comment]
What are the pros and cons of using our own workflow vs. the RTD github action to generate previews? cc @jbusecke

**Comment by jbusecke** [comment]
I dont have any experience with rolling docs preview manually, but from my experience, RTD can be quite slow (often being the last item of CI that finishes). If this approach is faster, I think that would be a really nice addition!
The downside (I guess) might be that the preview might not use the exact same dependencies and could potentially be slightly different from the final one built on RTD?

**Comment by charlesbluca** [comment]
If the rolling docs feature is essentially the same as my workflow (giving previews of what documentation would look like after a PR), then I'm happy to use that instead!

My workflow is still pretty hacked together, so there are plenty of cons to look out for:

- Populating the repo with `-preview` branches to be deleted later
- Resulting in unexpected behavior if we create branches ending in `-preview`
- Giving motivation to change our main CI in the first place

Is there documentation anywhere on RTD's preview functionality?

**Comment by jbusecke** [comment]
https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by charlesbluca** [comment]
Thanks! I'll play around with this for now and see how well it performs compared to the workflow.

**Comment by jbusecke** [comment]
Awesome. Let me know what you find out. Very curious about this.

**Comment by charlesbluca** [comment]
Opened up a PR #32 to test out autobuild, but it doesn't seem to show RTD in the checks - according to the [troubleshooting section](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html#troubleshooting), it looks like this might be because RTD isn't authorized as an app in this organization, or the webhooks need to be reconfigured? I'll look into that, but if an org owner could confirm whether or not RTD is authorized that would be great.

**Comment by jbusecke** [comment]
I had a similar issue in another repo. @rabernat was both the owner and able to figure it out. So maybe he can provide some input?

**Comment by TomAugspurger** [comment]
@charlesbluca can you try pushing another commit. I may have just authorized RTD's oauth application for pangeo-forge. Not 100% sure though.

**Comment by rabernat** [comment]
I got a notification that RTD was authorized for this repo.

**Comment by charlesbluca** [comment]
Sure! I'll push another commit to my PR and see if it works out.

**Comment by charlesbluca** [comment]
It looks like we still aren't getting RTD checks showing. On top of that, it looks like the docs build failed upon merging Ryan's big PR, though we still don't have any indication of why. 😕

If the OAuth is authorized, it _could_ be an issue with the webhook set up on RTD's side - maybe resyncing it could fix things?

**Comment by charlesbluca** [comment]
@rabernat @jhamman I added you both as maintainers on RTD - this should make the build failures more accessible for the time being while we sort out these checks.

**Comment by cisaacstern** [comment]
RTD works, thanks to these early efforts! Closing.
