### ISSUE TITLE
Release 0.8.0 by ~ Friday Feb 25

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#290]
We have an ESIP tutorial on Monday Feb 28. It would be good to get recent updates released before then. Let's plan to release 0.7.1 by ~ Friday Feb 25.

**Comment by rabernat** [comment]
I think we need to go directly to 0.8, given the major change introduced in #276.

Let's release it today. Why not?

**Comment by cisaacstern** [comment]
> Why not?

No reason! I'll do that now.

**Comment by cisaacstern** [comment]
> Let's make sure to update the whats-new page to highly clearly that there is a breaking change in the recipe API.

How does https://pangeo-forge--291.org.readthedocs.build/en/291/development/release_notes.html#v0-8-0-2022-02-17 look?

**Comment by rabernat** [comment]
Looks good, but makes me realize that we can't release this feature without a API and narrative documatation for `StorageConfig` here https://pangeo-forge--291.org.readthedocs.build/en/291/recipe_user_guide/storage.html

**Comment by cisaacstern** [comment]
Good call I will add that now

**Comment by cisaacstern** [comment]
> API and narrative documatation for StorageConfig

https://pangeo-forge--291.org.readthedocs.build/en/291/recipe_user_guide/storage.html

Anything to change or good to release?

**Comment by cisaacstern** [comment]
> https://pangeo-forge--291.org.readthedocs.build/en/291/recipe_user_guide/storage.html

> Anything to change or good to release?

IMHO this covers the requested scope. Going to merge https://github.com/pangeo-forge/pangeo-forge-recipes/pull/291 and release `0.8.0` now. Happy to improve docs in follow-up issues.
