### ISSUE TITLE
Add rubric for choosing a recipe class 

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#306]
Referenced in review https://github.com/pangeo-forge/pangeo-forge-recipes/pull/303#pullrequestreview-896351781

**Comment by cisaacstern** [comment]
There are no longer recipe classes as of `0.10.0`, so closing.

For those interested in learning more, see **What's Changed?** heading in https://medium.com/pangeo/pangeo-forge-is-all-in-on-apache-beam-d7370299405f.
