### ISSUE TITLE
Setting time encoding correctly for hourly data

### ISSUE THREAD

**Issue by jmunroe** [pangeo-forge/pangeo-forge-recipes#318]
When trying to create a recipe to concatenate netcdf files at hourly resolution ( https://github.com/pangeo-forge/staged-recipes/pull/119) we encountered an issue:

@jmunroe reported

> The recipe had issues concatenating the times. This dataset is hourly but the time were concatenated as daily. I've double checked that the datafile have the correct times. Running the recipe locally on all 84 files shows the time access only changing by "day" and not by hour.
> 
>  Is there some sort of "unit of time" option I need to pass to XarrayZarrRecipe? Or is there internal assumption that data files that are being concatenated are per day rather than letting Xarray do the concat operation?

@rabernat replied

> I think the issue is that xarray automatically determines the time encoding by looking at, just the first input, and then reuses that encoding for all the others. In this case, it chose:
> 
```
ds = xr.open_zarr(mapper, consolidated=True, decode_times=False)
ds.time.attrs
{'axis': 'T',
 'calendar': 'proleptic_gregorian',
 'long_name': 'Validity time',
 'standard_name': 'time',
 'units': 'days since 2022-03-03 00:00:00'}
```
> together with an integer dtype for time. This would not have happened if it had had multiple timesteps to look at.
> 
> So we could either:
> 
> - manually override the encoding for time
> - change the logic for how the dataset is initialized

**Comment by jmunroe** [comment]
XarrayZarrRecipe strips out all of the encodings for all variables by default.  Although this can be prevented by setting `delete_input_encoding = False`. I assume we do want to scrub almost all of these encodings.

Without a given encoding for "time",  `.to_zarr()` is applying CF-1.6, the standard variable "time" is being encoded as the number of *days* from the time stamp of the first file. Since we are only looking at the first file when preparing the zarr target, the recipe has no information on the rest of the files in the file pattern.   Even though Xarray can consider the number of days to be fractional (float), in the zarr file the dtype is converted to an integer.  

However, after the encodings are removed, then the recipe calls the options `process_input()` user supplied function.  In this function we can specify whatever encoding for time is most appropriate and `.to_zarr()` will use that encoding.  A function like

```
def process_input(ds, filename):
    ds['time'].encoding = {'units': 'hours since 2022-03-03 00:00:00',  'calendar': 'proleptic_gregorian'}
    
    return ds
```

let's us specific the encoding for time we want to use.

**Comment by martindurant** [comment]
Note that zarr stores timestamps perfectly well, with a range of resolutions to extend to all epochs. kerchunk can do this, by *not* using xarray to create datasets.

**Comment by rabernat** [comment]
@martindurant - do you know if xarray can decode those timestamps?

I think the problem with the way Zarr stores timestamps is that they are Python objects and therefore can only be read by Python users. The way CF conventions encode time is more portable across languages.
