### ISSUE TITLE
Drop `pynio` dependency?

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#325]
As discussed in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/324#issuecomment-1065339106, `pynio` is unmaintained and cannot be installed from Conda Forge without causing conflicts with other dependencies. (The present conflict is with `ujson` but others could arise.)

> A workaround for this conflict is, for now, to install `kerchunk` (which brings in `ujson`) from `pip`.

Do we rely on xarray's PyNIO backend for anything? The xarray docs note that it [conflicts with recent `netcdf4` versions](https://xarray.pydata.org/en/stable/user-guide/io.html#formats-supported-by-pynio).

If we don't use PyNIO, perhaps it's best to remove it, which would allow installing `kerchunk` from Conda Forge (and prevent other such conflicts in the future).

**Comment by rabernat** [comment]
:+1: from me. But we have to be aware that some GRIB files may become inaccessible.

**Comment by cisaacstern** [comment]
Sounds good. I suggest we wrap up #324 first, then I'll put this in as it's own PR.

**Comment by cisaacstern** [comment]
xref https://github.com/conda-forge/pynio-feedstock/issues/114
