### ISSUE TITLE
OG image links are broken again

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#333]
On view-source:https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/tutorials/xarray_zarr/cmip6-recipe.html the OG:image link is broken

```
<meta property="og:image" content="https://pangeo-forge.readthedocs.io/_images/cmip6-recipe_39_1.png" />
```

I thought we had fixed that by pinning

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/186095adcbb0a18ee1c2b3b84451cdb26fd1372c/docs/requirements.txt#L9

as described in https://github.com/wpilibsuite/sphinxext-opengraph/issues/59

**Comment by ItayZiv** [comment]
This should be fixed in https://github.com/wpilibsuite/sphinxext-opengraph/releases/tag/v0.6.3

**Comment by rabernat** [comment]
Thanks so much for the quick fix! 🚀
