### ISSUE TITLE
'OSError: [Errno 63] File name too long' when running recipe locally

### ISSUE THREAD

**Issue by paigem** [pangeo-forge/pangeo-forge-recipes#346]
I am running into an `OSError: [Errno 63] File name too long` when I try to run my draft recipe locally. It looks like this dataset has a particularly long url, which is causing trouble when this is converted to a file name. I have gotten the same error running on my local MacBook Pro (OS 11.6) and Pangeo's Google Cloud deployment. Running Pangeo Forge version `0.8.2`.

I am including the code to reproduce this error below, with the full error message as well.

```python
from pangeo_forge_recipes.recipes import XarrayZarrRecipe
from pangeo_forge_recipes.patterns import FilePattern, ConcatDim, MergeDim

# only do two years to keep the example small
years = list(range(46,48))
variables = [
    "LHFLX",
    "SHFLX",
]

def make_filename(variable, time):
    return ("https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cesm/collections/ASD/"
            "hybrid_v5_rel04_BC5_ne120_t12_pop62/atm-regrid/proc/tseries/daily/FV_768x1152.bilinear."
            f"hybrid_v5_rel04_BC5_ne120_t12_pop62.cam.h1.{variable}.00{time}0101-00{time}1231.nc")
            
            
pattern = FilePattern(
    make_filename,
    ConcatDim(name="time", keys=years),
    MergeDim(name="variable", keys=variables)
)

# Define the recipe
target_chunks = {"time": 30} 

recipe = XarrayZarrRecipe(
            file_pattern=pattern,
            target_chunks=target_chunks)

# Run locally
from pangeo_forge_recipes.recipes import setup_logging
setup_logging()
run_function = recipe.to_function()
run_function()
```

<details><summary>Output OSError</summary>
pangeo_forge_recipes.recipes.xarray_zarr - INFO - Caching input 'Index({DimIndex(name='variable', index=0, sequence_len=2, operation=<CombineOp.MERGE: 1>), DimIndex(name='time', index=0, sequence_len=2, operation=<CombineOp.CONCAT: 2>)})'
pangeo_forge_recipes.storage - INFO - Caching file 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cesm/collections/ASD/hybrid_v5_rel04_BC5_ne120_t12_pop62/atm-regrid/proc/tseries/daily/FV_768x1152.bilinear.hybrid_v5_rel04_BC5_ne120_t12_pop62.cam.h1.LHFLX.00460101-00461231.nc'
pangeo_forge_recipes.storage - INFO - Copying remote file 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cesm/collections/ASD/hybrid_v5_rel04_BC5_ne120_t12_pop62/atm-regrid/proc/tseries/daily/FV_768x1152.bilinear.hybrid_v5_rel04_BC5_ne120_t12_pop62.cam.h1.LHFLX.00460101-00461231.nc' to cache
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [26], in <cell line: 1>()
----> 1 run_function()

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/pangeo_forge_recipes/executors/python.py:44, in FunctionPipelineExecutor.compile.<locals>.function()
     42 if stage.mappable is not None:
     43     for m in stage.mappable:
---> 44         stage.function(m, config=pipeline.config)
     45 else:
     46     stage.function(config=pipeline.config)

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/pangeo_forge_recipes/recipes/xarray_zarr.py:151, in cache_input(input_key, config)
    149     logger.info(f"Caching input '{input_key!s}'")
    150     fname = config.file_pattern[input_key]
--> 151     config.storage_config.cache.cache_file(
    152         fname,
    153         config.file_pattern.query_string_secrets,
    154         **config.file_pattern.fsspec_open_kwargs,
    155     )
    157 if config.cache_metadata:
    158     if config.storage_config.metadata is None:

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/pangeo_forge_recipes/storage.py:166, in CacheFSSpecTarget.cache_file(self, fname, secrets, **open_kwargs)
    164 target_opener = self.open(fname, mode="wb")
    165 logger.info(f"Copying remote file '{fname}' to cache")
--> 166 _copy_btw_filesystems(input_opener, target_opener)

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/pangeo_forge_recipes/storage.py:38, in _copy_btw_filesystems(input_opener, output_opener, BLOCK_SIZE)
     36 def _copy_btw_filesystems(input_opener, output_opener, BLOCK_SIZE=10_000_000):
     37     with input_opener as source:
---> 38         with output_opener as target:
     39             start = time.time()
     40             interval = 5  # seconds

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/contextlib.py:135, in _GeneratorContextManager.__enter__(self)
    133 del self.args, self.kwds, self.func
    134 try:
--> 135     return next(self.gen)
    136 except StopIteration:
    137     raise RuntimeError("generator didn't yield") from None

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/pangeo_forge_recipes/storage.py:123, in FSSpecTarget.open(self, path, **kwargs)
    121 full_path = self._full_path(path)
    122 logger.debug(f"entering fs.open context manager for {full_path}")
--> 123 of = self.fs.open(full_path, **kwargs)
    124 logger.debug(f"FSSpecTarget.open yielding {of}")
    125 yield of

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/fsspec/spec.py:1009, in AbstractFileSystem.open(self, path, mode, block_size, cache_options, compression, **kwargs)
   1007 else:
   1008     ac = kwargs.pop("autocommit", not self._intrans)
-> 1009     f = self._open(
   1010         path,
   1011         mode=mode,
   1012         block_size=block_size,
   1013         autocommit=ac,
   1014         cache_options=cache_options,
   1015         **kwargs,
   1016     )
   1017     if compression is not None:
   1018         from fsspec.compression import compr

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/fsspec/implementations/local.py:155, in LocalFileSystem._open(self, path, mode, block_size, **kwargs)
    153 if self.auto_mkdir and "w" in mode:
    154     self.makedirs(self._parent(path), exist_ok=True)
--> 155 return LocalFileOpener(path, mode, fs=self, **kwargs)

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/fsspec/implementations/local.py:250, in LocalFileOpener.__init__(self, path, mode, autocommit, fs, compression, **kwargs)
    248 self.compression = get_compression(path, compression)
    249 self.blocksize = io.DEFAULT_BUFFER_SIZE
--> 250 self._open()

File ~/opt/anaconda3/envs/pangeo-forge/lib/python3.10/site-packages/fsspec/implementations/local.py:255, in LocalFileOpener._open(self)
    253 if self.f is None or self.f.closed:
    254     if self.autocommit or "w" not in self.mode:
--> 255         self.f = open(self.path, mode=self.mode)
    256         if self.compression:
    257             compress = compr[self.compression]

OSError: [Errno 63] File name too long: '/var/folders/kp/4b8drk090qn632t3j69yth0r0000gn/T/tmpez7zy_jy/IODtnoma/7420dff26e6e13dd29495cd56f1dd7af-https_tds.ucar.edu_thredds_fileserver_datazone_campaign_cesm_collections_asd_hybrid_v5_rel04_bc5_ne120_t12_pop62_atm-regrid_proc_tseries_daily_fv_768x1152.bilinear.hybrid_v5_rel04_bc5_ne120_t12_pop62.cam.h1.lhflx.00460101-00461231.nc'
</details>

**Comment by rabernat** [comment]
This seems relevant: https://serverfault.com/questions/9546/filename-length-limits-on-linux

It looks like the filename `/var/folders/kp/4b8drk090qn632t3j69yth0r0000gn/T/tmpez7zy_jy/IODtnoma/7420dff26e6e13dd29495cd56f1dd7af-https_tds.ucar.edu_thredds_fileserver_datazone_campaign_cesm_collections_asd_hybrid_v5_rel04_bc5_ne120_t12_pop62_atm-regrid_proc_tseries_daily_fv_768x1152.bilinear.hybrid_v5_rel04_bc5_ne120_t12_pop62.cam.h1.lhflx.00460101-00461231.nc` violates the 255-bytes-per-filename constraint

```python
name = '/var/folders/kp/4b8drk090qn632t3j69yth0r0000gn/T/tmpez7zy_jy/IODtnoma/7420dff26e6e13dd29495cd56f1dd7af-https_tds.ucar.edu_thredds_fileserver_datazone_campaign_cesm_collections_asd_hybrid_v5_rel04_bc5_ne120_t12_pop62_atm-regrid_proc_tseries_daily_fv_768x1152.bilinear.hybrid_v5_rel04_bc5_ne120_t12_pop62.cam.h1.lhflx.00460101-00461231.nc'

for part in name.split('/'):
    print(len(part))
```

I recommend truncating the name here:

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/0d8694a4908df4d3b99f416709311db68aa71285/pangeo_forge_recipes/storage.py#L141-L146

However, it would be nice to preserve the suffix (here `.nc`).
