### ISSUE TITLE
BaseRecipe methods not documented

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#352]
https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/api_reference.html?highlight=hash#module-pangeo_forge_recipes.recipes

<img width="627" alt="image" src="https://user-images.githubusercontent.com/1197350/166103416-dbf7dc41-08f2-4683-8517-66a078e59084.png">

This is generated by

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/cc0a1be49c3d37dcb1713fd1c8e6bc2725a8d22f/docs/pangeo_forge_recipes/api_reference.md?plain=1#L43-L48

For some reason, it's seeing the class itself but not detecting any of the methods.

**Comment by cisaacstern** [comment]
This class no longer exists as of `0.10.0`, so closing.
