### ISSUE TITLE
Subsetting along non-concat dim results in truncated dataset

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#360]
In our tests, we only cover the scenario where subsetting and concatenation happen along the same dimension (time)

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/2c69fd7752b81db514677088f526a35f418f95c1/tests/recipe_tests/test_XarrayZarrRecipe.py#L81-L89

However, if we try to subset along a different dimension (e.g. `subset_inputs={'lat': 2}`), we are not able to initialize the target correctly. It gets truncated. This has been reported in
- https://github.com/pangeo-forge/staged-recipes/pull/127#issuecomment-1083336512
- https://github.com/pangeo-forge/staged-recipes/pull/133#issuecomment-1121132064

This will require some changes to `prepare_target` to fix.

The workaround for now is to simply not use `subset_inputs` along non-concat dimensions.

**Comment by cisaacstern** [comment]
The `subset_inputs` option no longer exists in `0.10.0`, so closing.
