### ISSUE TITLE
Augment Index index with start & stop 

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#367]
As per discussion today, we want to do the following in `patterns.py`

```diff
@dataclass(frozen=True, order=True)
class DimIndex:
    name: str
    index: int
    sequence_len: int
    operation: CombineOp
+   start: Optional[int]
+   stop: Optional[int]
```
`start` and `stop` represent the explicit absolute array index location of the data in this chunk in the full dataset. So to insert the data, you would do (assuming 1D)
```python
target[dim_index.start:dim_index.stop] = data_from_chunk
```

We also want to write a standalone function of the form

```python
augment_index_with_start_stop(index: DimIndex, sequence_lens: List[int]) -> DimIndex:
    # take an index _without_ start / stop and add them based on the lens defined in sequence_lens
    assert len(sequence_lens) == index.sequence_len
    start = sum(sequence_lens[:index.index])
    stop = start + sequence_lens[index.index]
    # return a new dimindex because it's frozen
``` 
`sequence_lens` is the list of the lens of _all the items in the sequence_ including this one.

This can be unit tested with synthetic data.

**Comment by cisaacstern** [comment]
Strangely this was not auto-closed when #372 was merged, so closing now.
