### ISSUE TITLE
Issue on page /grid_ufuncs.html

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-forge/pangeo-forge-recipes#368]
In cell [2], where diff_forward is defined. It seems like it has been defined in the opposite sense of the usual. 
The usual definition would be diff_a = a[i+1] - a[i], whereas (if I understand roll correctly) it seems that here the function is calculating diff_a = a[i] - a[i+1]. (so there is a sign error). 

Also, regardless of the sign error the diff_a would be a variable that ends up on ax1:right, but instead in the paragraph below it seems to suggest that things end up on ax1:left (which is what would happen if we were doing a backward difference.

**Comment by cisaacstern** [comment]
@dhruvbalwada, maybe this issue was intended for another repo?

**Comment by dhruvbalwada** [comment]
Huh, yes it was. Sorry about this. 
I raised this issue using the xgcm documentation - the little github button on the top right of the page. Maybe the linking in the xgcm doc has a bug. 
@jbusecke @TomNicholas
<img width="925" alt="Screen Shot 2022-05-24 at 4 59 15 PM" src="https://user-images.githubusercontent.com/18236610/170131327-8aa8cb24-0def-4fad-afb4-a25753066f62.png">
