### ISSUE TITLE
Can additional dataset attributes be specified to XarrayZarrRecipe?

### ISSUE THREAD

**Issue by derekocallaghan** [pangeo-forge/pangeo-forge-recipes#378]
Hi,

I'm currently putting together a staged-recipes contribution, and wanted to check whether it's possible to specify additional attributes to be included in the output Zarr dataset generated by `XarrayZarrRecipe`? I've had a look through the documentation, issues and code here and it looks like it isn't possible, but I thought I'd confirm it if that's okay. The closest I can see is the possible inclusion of something like `XarrayZarrRecipe(...,xarray_concat_kwargs={'combine_attrs': ...})`

Thanks,
Derek

**Comment by rabernat** [comment]
This would currently be possible via a preprocessor function, i.e.

```python
def add_attribute(ds):
    ds.attrs['foo'] = 'bar'
    return ds

recipe = XarrayZarrRecipe(
    process_chunks=add_attribute
)
```

**Comment by derekocallaghan** [comment]
Perfect, thanks Ryan. I've added it to my existing preprocessor and confirmed it works.
