### ISSUE TITLE
Raster data support

### ISSUE THREAD

**Issue by norlandrhagen** [pangeo-forge/pangeo-forge-recipes#392]
Hi there,

Wondering if `.TIFF` files were supported in the `XarrayZarrRecipe`. 

In this blurb from the docs, it seems to be possible: 
```The inputs can be in any [file format Xarray can read](http://xarray.pydata.org/en/latest/user-guide/io.html), including NetCDF, OPeNDAP, GRIB, Zarr, and, via [rasterio](https://rasterio.readthedocs.io/), GeoTIFF and other geospatial raster formats. T```

When trying to make use of rioxarray for opening up the file, I set `{'engine': 'rasterio'}`, but got this error.

```ValueError: pangeo-forge-recipes will automatically set the xarray backend for files of type 'netcdf4' to '{'engine': 'h5netcdf'}', which is different from the value you have passed via `xarray_open_kwargs`. If this input file is actually of type 'netcdf4', please remove `{'engine': 'rasterio'}` from `xarray_open_kwargs`. If this input file is not of type 'netcdf4', please update this recipe by passing a different value to `FilePattern.file_type`.```

I also tried to specify the `file_type` in the [`FilePattern`](https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/api_reference.html?highlight=api#file-patterns), but couldn't find a accepted file format. 

It seems like `tiff/geotiff` isn't an option in [`patterns.py#L111`](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/d1875c3f483188ed72e34177c58bc896b947aa76/pangeo_forge_recipes/patterns.py#L111)

Anyhow, just wondering if there are any example recipes using rioxarray or if anyone has any advice on how to proceed.

cc @cisaacstern 

Thanks!

**Comment by cisaacstern** [comment]
This recipe uses raster data: https://github.com/pangeo-forge/staged-recipes/pull/133

But it was written before the `file_type` kwarg was added to FilePattern.

To make this work now, we'd need a PR adding `tiff` to the options for FilePattern. Feel free to have a go at that if you'd like!

While that's in progress, downgrading to `pangeo-forge-recipes==0.8.2` will allow you to run the recipe with `{'engine': 'rasterio'}` without hitting the ValueError.

**Comment by norlandrhagen** [comment]
Sounds good! I'll open up a PR adding `tiff`.

**Comment by cisaacstern** [comment]
Awesome, feel free to ping me with any questions about that!

**Comment by norlandrhagen** [comment]
Note. This issue was closed from this PR: https://github.com/pangeo-forge/pangeo-forge-recipes/pull/393
