### ISSUE TITLE
Adding a rechunker step

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#40]
The initial chunk structure of a dataset will always be dictated by the inputs: if it's a sequence of netCDFs in time, then we will get a Zarr dataset chunked in time. However, once we have that Zarr, we can easily rechunk it with rechunker. We have explicitly borrowed the pipeline / executor architecture from rechunker to facilitate this integration.

Some questions:
- Is rechunking a _separate_ recipe? Or can it be chained as part of a single recipe?
- What API syntax should a rechunking recipe use?
- At what point in the recipe execution sequence does the rechunking happen?

**Comment by cisaacstern** [comment]
As of `0.10.0`, this is now builtin to `StoreToZarr` 🙌 , so closing.
