### ISSUE TITLE
ConcatDim with different sized source files

### ISSUE THREAD

**Issue by nbren12** [pangeo-forge/pangeo-forge-recipes#441]
An ERA5 dataset I am working with has differing number of times per file. Does pangeo-forge-recipes allow this?

**Comment by cisaacstern** [comment]
Yes. In this case, do _**not**_ use the [`nitems_per_file` option on `ConcatDim`](https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/recipe_user_guide/file_patterns.html#specifying-nitems-per-file-in-a-concatdim), which is only for sets of input files with a uniform number of timesteps per file.

Instead, define chunking at the recipe level with, in `XarrayZarrRecipe`, e.g., the `inputs_per_chunk` or `target_chunks` kwargs.

**Comment by nbren12** [comment]
Thanks. Closing.
