### ISSUE TITLE
Decide what happens to Dask & Prefect executors once beam-refactor is merged

### ISSUE THREAD

**Issue by yuvipanda** [pangeo-forge/pangeo-forge-recipes#475]
Would these be removed? @rabernat what is your current thought process here?

My personal suggestion is that we remove them :)

**Comment by cisaacstern** [comment]
I would agree, removing them makes sense to me.

**Comment by rabernat** [comment]
Remove. 👋

**Comment by yuvipanda** [comment]
Great, who wants to do it? :D
