### ISSUE TITLE
Docs bug on `latest`

### ISSUE THREAD

**Issue by norlandrhagen** [pangeo-forge/pangeo-forge-recipes#477]
I took a look at the docs page this morning and was getting some strange behavior. I'm on an M1 mac and on both Firefox and Chrome the [latest docs](https://pangeo-forge.readthedocs.io/en/latest/) build doesn't seem to render correctly.  Links on the left hand side of the page and in the center don't work, while the right hand contents menu works fine. 
Changing to [stable](https://pangeo-forge.readthedocs.io/en/stable/index.html) fixes the issue. 

Firefox:
<img width="1435" alt="Screen Shot 2023-01-17 at 12 01 52 PM" src="https://user-images.githubusercontent.com/22455466/212988684-2b1cae60-3b25-4289-9540-fe9730c7e8fa.png">

Chrome:
<img width="1435" alt="Screen Shot 2023-01-17 at 12 02 16 PM" src="https://user-images.githubusercontent.com/22455466/212988721-b0930fad-984a-48a0-b5f9-361ff2ad8830.png">

**Comment by rabernat** [comment]
🤦  That sucks.

Usually this means that something in our doc stack (sphinx, jupyter book theme, etc.) has made a new release. If you can figure out what has changed recently from examining the CI logs, we can probably fix this by pinning a version.

Or maybe it has fixed itself. If you look at one of our most recent PRs (e.g. #476), the site looks fine: https://pangeo-forge--476.org.readthedocs.build/en/476/

**Comment by rabernat** [comment]
I merged #469 hoping it would just fix things. Its [preview](https://pangeo-forge--469.org.readthedocs.build/en/476/) looks fine. But https://pangeo-forge.readthedocs.io/en/latest/ still looks messed up.

😩

@norlandrhagen - do you have any insight into what might be going on?

**Comment by cisaacstern** [comment]
Could this be related to https://github.com/pangeo-forge/pangeo-forge-recipes/pull/461, which was merged an hour ago?

**Comment by rabernat** [comment]
You mean the PR where we bumped sphinx by **two major versions**? Um yea that might be it! 😆

**Comment by norlandrhagen** [comment]
I can open up a PR to revert that and see fixes it?

**Comment by cisaacstern** [comment]
Yes that would be great, thanks @norlandrhagen!
