### ISSUE TITLE
[beam-refactor] Remove Non-Beam Reference Recipe

### ISSUE THREAD

**Issue by norlandrhagen** [pangeo-forge/pangeo-forge-recipes#494]
Related to https://github.com/pangeo-forge/pangeo-forge-recipes/pull/493 and https://github.com/pangeo-forge/pangeo-forge-recipes/pull/489, references to non-Beam reference recipes should be removed.

**Comment by cisaacstern** [comment]
Completed in #509

**Comment by cisaacstern** [comment]
Completed in #509
