### ISSUE TITLE
Port `XarrayZarrRecipe.subset_inputs` to `beam-refactor`

### ISSUE THREAD

**Issue by derekocallaghan** [pangeo-forge/pangeo-forge-recipes#496]
`XarrayZarrRecipe` provides a `subset_inputs` feature:

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/45cc115f287ca7d33c33aaa343f21c862812c0bb/pangeo_forge_recipes/recipes/xarray_zarr.py#L762-L765

This is currently used by the [*NARR: Subsetting and OPeNDAP* tutorial notebook](https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/tutorials/xarray_zarr/opendap_subset_recipe.html#define-the-recipe). I checked the `beam-refactor` branch but I don't see an equivalent, where the only mention of subsetting is related to rechunking.

If it's the case that we no longer want to support this feature, this issue can be closed.

**Comment by rabernat** [comment]
We no longer need this feature. The beam refactor automatically handles sub-sampling into the target chunks.
