### ISSUE TITLE
Zarr to Zarr capabilites?

### ISSUE THREAD

**Issue by kbren** [pangeo-forge/pangeo-forge-recipes#501]
I'm interested in using pangeo-forge-recipes to do pre-processing and re-chunking of various large Zarr datasets that are already on GCP. In the documentation for the XarrayZarrRecipe class (https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/recipe_user_guide/recipes.html) it says the inputs can be "any file format Xarray can read, including NetCDF, OPeNDAP, GRIP, Zarr." However, when I input Zarr files to `FilePattern()` with the `file_type='zarr'` keyword argument and then build and try to run a recipe I get an error:
```
OSError: [Errno -36] NetCDF: Invalid argument
```

I also note that `FileType.Zarr` is set to be an unopenable file type: 
https://github.com/pangeo-forge/pangeo-forge-recipes/blob/45cc115f287ca7d33c33aaa343f21c862812c0bb/pangeo_forge_recipes/recipes/xarray_zarr.py#L56

Is this an error in the documentation or are there plans to make Zarr to Zarr recipes possible? OR are they already possible and I'm messing up keyword arguments? 

Thanks!

**Comment by rabernat** [comment]
Hi Katie! This will definitely be supported in the next release of Pangeo Forge (see #369).

**Comment by kbren** [comment]
Awesome thanks for the quick reply Ryan! Any estimates on that release date?

**Comment by rabernat** [comment]
Hopefully by the end of the week!
