### ISSUE TITLE
`recipe.reference_hdf_zarr.scan_file` overwrites keys with the same basename, drops references

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-forge/pangeo-forge-recipes#515]
In https://github.com/pangeo-forge/pangeo-forge-recipes/blob/45cc115f287ca7d33c33aaa343f21c862812c0bb/pangeo_forge_recipes/recipes/reference_hdf_zarr.py#L29, we call `os.path.basename` on the filename of the input. When two input files have different directories (prefixes in blob storage) but the same basename, we'll repeatedly overwrite the reference at that key. This will cause the `references` output to drop some of the files.

Here's a somewhat minimal example (requires adlfs). Notice that the `urls` differ only by the directory `nwm.20220629` vs. `nwm.20220630`

```python
import fsspec
import json
import xarray as xr
from pangeo_forge_recipes.patterns import pattern_from_file_sequence
from pangeo_forge_recipes.recipes.reference_hdf_zarr import HDFReferenceRecipe

fsspec.filesystem("abfs", account_name="noaanwm")

urls = [
    "abfs://nwm/nwm.20220629/short_range/nwm.t00z.short_range.channel_rt.f001.conus.nc",
    "abfs://nwm/nwm.20220630/short_range/nwm.t00z.short_range.channel_rt.f001.conus.nc",
]

pattern = pattern_from_file_sequence(urls, "time")
recipe = HDFReferenceRecipe(
    pattern,
    netcdf_storage_options={"account_name": "noaanwm"},
    inline_threshold=500_000,
)

recipe.to_dask().compute()

d = json.loads(open(f"{recipe.storage_config.target.root_path}/reference.json").read())
m = fsspec.get_mapper(
    "reference://",
    fo=d,
    remote_options={"account_name": "noaanwm"},
    target_options={"account_name": "noaanwm"},
    skip_instance_cache=True,
    remote_protocol="abfs",
)

ds = xr.open_dataset(m, engine="zarr", consolidated=False, chunks={"time": 1})

assert ds.time.shape[0] == 2

```

That assertion fails.

Here's a workaround, which redefines `scan_file` to not call `os.path.basename` (plus some stuff to get it used by the recipe).

<details>

```
import fsspec
import json
import xarray as xr
from pangeo_forge_recipes.patterns import pattern_from_file_sequence
from pangeo_forge_recipes.recipes.reference_hdf_zarr import HDFReferenceRecipe

from pangeo_forge_recipes.recipes.reference_hdf_zarr import (
    ChunkKey,
    HDFReferenceRecipe,
    Stage,
    unstrip_protocol,
    file_opener,
    create_kerchunk_reference,
    Pipeline,
    finalize,
)

fsspec.filesystem("abfs", account_name="noaanwm")


def scan_file(chunk_key: ChunkKey, config: HDFReferenceRecipe):
    assert config.storage_config.metadata is not None, "metadata_cache is required"
    fname = config.file_pattern[chunk_key]
    ref_fname = fname + ".json"
    with file_opener(fname, **config.netcdf_storage_options) as fp:
        protocol = getattr(getattr(fp, "fs", None), "protocol", None)  # make mypy happy
        if protocol is None:
            raise ValueError("Couldn't determine protocol")
        target_url = unstrip_protocol(fname, protocol)
        config.storage_config.metadata[ref_fname] = create_kerchunk_reference(
            fp, target_url, file_type=config.file_pattern.file_type
        )


def hdf_reference_recipe_compiler(recipe: HDFReferenceRecipe) -> Pipeline:
    stages = [
        Stage(
            name="scan_file", function=scan_file, mappable=list(recipe.iter_inputs())
        ),
        Stage(name="finalize", function=finalize),
    ]
    return Pipeline(stages=stages, config=recipe)


class MyHDFReferenceRecipe(HDFReferenceRecipe):
    _compiler = hdf_reference_recipe_compiler


urls = [
    "abfs://nwm/nwm.20220629/short_range/nwm.t00z.short_range.channel_rt.f001.conus.nc",
    "abfs://nwm/nwm.20220630/short_range/nwm.t00z.short_range.channel_rt.f001.conus.nc",
]

pattern = pattern_from_file_sequence(urls, "time")
recipe = MyHDFReferenceRecipe(
    pattern,
    netcdf_storage_options={"account_name": "noaanwm"},
    inline_threshold=500_000,
)

recipe.to_dask().compute()

d = json.loads(open(f"{recipe.storage_config.target.root_path}/reference.json").read())
m = fsspec.get_mapper(
    "reference://",
    fo=d,
    remote_options={"account_name": "noaanwm"},
    target_options={"account_name": "noaanwm"},
    skip_instance_cache=True,
    remote_protocol="abfs",
)

ds = xr.open_dataset(m, engine="zarr", consolidated=False, chunks={"time": 1})

assert ds.time.shape[0] == 2
```

</details>

That assert passes.

**Comment by cisaacstern** [comment]
Thanks for raising this, Tom.

As you're aware, the bulk of our developer focus is on the beam refactor currently, but if getting this fix into a patch release would be useful to you, happy to support that!

**Comment by TomAugspurger** [comment]
Understood, and my workaround is sufficient for now.

I haven't kept up with the beam refactor, but it seems like https://github.com/pangeo-forge/pangeo-forge-recipes/pull/486 is the relevant PR for reference recipes. I skimmed through there, and didn't see anything quite like this issue. If we're confident that the beam refactor won't be using the same method, then I'm good to close this.

**Comment by cisaacstern** [comment]
> Thanks; my workaround is sufficient for now.

Great.

> seems like https://github.com/pangeo-forge/pangeo-forge-recipes/pull/486 is the relevant PR for reference recipes. I skimmed through there, and didn't see anything quite like this issue. If we're confident that the beam refactor won't be using the same method, then I'm good to close this.

Yes, #486 (which is nearly done!) is the right PR. And you are correct, this issue doesn't come into play there, because we actually _don't write the references out anywhere_. 😄 As [demonstrated in the integration tests](https://github.com/pangeo-forge/pangeo-forge-recipes/pull/486/files#diff-ed6dfac22b1faf172f5b38bfd6b2b67f991a9b047131ed0273d62c0b7da57ff6R168-R179) there, we simply pass the references as a beam PCollection from the `OpenWithKerchunk` transform directly to the `CombineReferences` transform, without ever assigning them names/keys. My (albeit introductory) knowledge of kerchunk, plus the evidence of the tests, seems to suggest this works. 🎉 

So I will close this, with thanks again for raising it!
