### ISSUE TITLE
Triage dependabot PRs against new default branch `main`

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#538]
In preparation to release our work in `beam-refactor`, I have made a new branch named `main` from `beam-refactor`, and then set `main` as the default branch.

Dependabot then opened #528 #529 #530 #531 #532 #533 ~~#534~~ #535 #536 and #537 against `main`.

We should triage these on a case-by-case basis, as I'm not certain we do want to upgrade everything being recommended here (or even if we do, let's do it carefully so we don't accidentally break something).

**Comment by derekocallaghan** [comment]
Hi @cisaacstern, it looks like #534 fixes the Previous/Next rendering issues in #502. They are rendered correctly in the corresponding docs build, e.g. the [*What is Pangeo Forge?* page](https://pangeo-forge--534.org.readthedocs.build/en/534/what_is_pangeo_forge.html#how-can-i-help-with-development).

**Comment by cisaacstern** [comment]
Just finished the rest of these, phew 😃
