### ISSUE TITLE
Is the Globus workaround from #408 still supported with v0.10.x?

### ISSUE THREAD

**Issue by jbusecke** [pangeo-forge/pangeo-forge-recipes#558]
I am discussing moving data from GFDL into LEAP/m2lines cloud buckets (with @adcroft), and just scrolled through some past issues/PRs on the matter (#222, #408). In particular I am wondering if the approach in #408 is still valid with the beam refactor. 
The parts of the docs seem to have been removed, but I am not sure why something in the `file_pattern` API would have necessarily changed, even though I might be missing something here. 

If this is generally still applicable Id be happy to try this out.

**Comment by rabernat** [comment]
Yes, it should absolutely still work! Why did the globus part of the docs disappear! 😢  It would be great to bring that back.

**Comment by rabernat** [comment]
It looks like the correct version of the docs are present on the master branch

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/master/docs/pangeo_forge_recipes/recipe_user_guide/file_patterns.md#globus

But not on main

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/main/docs/pangeo_forge_recipes/recipe_user_guide/file_patterns.md#globus
