### ISSUE TITLE
Define dynamic target chunks interface in `StoreToZarr`

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#572]
As discussed in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/546#issuecomment-1688854651, I think we should give users the option of bringing their own dynamic chunking function to generate target chunks from a schema in StoreToZarr. The linked comment contains a pseudocode example. This is an alternative to merging #546 into `pangeo-forge-recipes`, based on @jbusecke and my recognition that:

1. Users may want to define their own dynamic chunking approach; and
2. #546 is a _lot_ of code to maintain in this repo, probably too much for right now

**Comment by jbusecke** [comment]
Just dropping https://github.com/jbusecke/pangeo-forge-esgf/issues/11 here, as this would be a good usecase for another custom chunking implementation, that needs access to the full dataset but would presumably implement the algo differently. 
Really emphasizes how a general plug in structure would be a nice thing for the community.
