### ISSUE TITLE
`full_target.fs.protocol` returns multiple protocols

### ISSUE THREAD

**Issue by norlandrhagen** [pangeo-forge/pangeo-forge-recipes#629]
I'm trying to run a reference recipe and get a failure in `WriteCombinedReference`. In my recipe, `full_target.fs.protocol` returns a list `['s3', 's3a']`, which causes a TypeError `TypeError: unhashable type: `. 

Wondering how this should be handled if fsspec returns multiple protocols. 

Happy to open up a PR that adds the optional kwarg `remote_protocol` that is infered from fsspec if not explicitly stated, but not sure if that's a good solution.

Would love to hear your thoughts @cisaacstern!

**Comment by cisaacstern** [comment]
@norlandrhagen seems like fsspec takes the first protocol in case of multiple protocols, so we could do the same, like this:

> https://github.com/fsspec/filesystem_spec/blob/b8aeb13361e89f22f323bbc93c8308ff2ffede19/fsspec/spec.py#L1410-L1414

**Comment by norlandrhagen** [comment]
Sounds great! Where should that logic live?

**Comment by cisaacstern** [comment]
I would just put it right above where we currently have full_target.fs.protocol, since IIUC we only use that once in the code currently.

**Comment by norlandrhagen** [comment]
I think once [this](https://github.com/pangeo-forge/pangeo-forge-recipes/pull/632) is merged, this can be closed

**Comment by cisaacstern** [comment]
Closed by #632 💫
