### ISSUE TITLE
Minio tests failing

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-recipes#645]
We need a follow-on to #638 that restores the

```python
assert proc.returncode == 0
```
because both of the minio test cases are failing:

> https://github.com/pangeo-forge/pangeo-forge-recipes/actions/runs/6777276247/job/18420542826#step:7:32

> https://github.com/pangeo-forge/pangeo-forge-recipes/actions/runs/6777276247/job/18420542826#step:7:317

but without that assert they are registering to pytest as passes.

_Originally posted by @cisaacstern in https://github.com/pangeo-forge/pangeo-forge-recipes/issues/638#issuecomment-1796994135_

**Comment by ranchodeluxe** [comment]
and we're good after that merge: https://github.com/pangeo-forge/pangeo-forge-recipes/actions/runs/6852898330/
