### ISSUE TITLE
`write_combined_reference` on `main` doesn't reuse dep injected `FSSpecTarget` credentials

### ISSUE THREAD

**Issue by ranchodeluxe** [pangeo-forge/pangeo-forge-recipes#666]
### Problem
There seems to be a regression on `main` compared to `0.10.4` release where `write_combined_reference` doesn't use the dep injected credentials from `FSSpecTarget`. 

I see [a thread in the merged PR](https://github.com/pangeo-forge/pangeo-forge-recipes/pull/660#discussion_r1451732656) for this regression there was some confusion about this and that `target_options` and `remote_options` was a work around.

### Possible Solution
In `0.10.4`[ this context manager block was doing the magic](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/0.10.4/pangeo_forge_recipes/writers.py#L123). I assume we can add that back and remove all the `remote_options` and `target_options` in favor of dep injection just like `StoreToZarr` works? Thoughts?

**Comment by norlandrhagen** [comment]
Great digging @ranchodeluxe! Do you want to open a PR fix for this or would you prefer to review?

In summary for the fix:
- Re-implement this [context manager](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/0.10.4/pangeo_forge_recipes/writers.py#L123).
- tear out any mention of `remote_options` and `target_options`.

We have those minio integration tests for AWS recipes. Are there any _global os environment AWS_* credentials_ that need to be added/updated to the minio config for this to work?

**Comment by ranchodeluxe** [comment]
> Great digging @ranchodeluxe! Do you want to open a PR fix for this or would you prefer to review?
> 
> In summary for the fix:
> 
>     * Re-implement this [context manager](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/0.10.4/pangeo_forge_recipes/writers.py#L123).
> 
>     * tear out any mention of `remote_options` and `target_options`.

I didn't know I had options! I can put in a fix tomorrow

> We have those minio integration tests for AWS recipes. Are there any _global os environment AWS_* credentials_ that need to be added/updated to the minio config for this to work?

Our integration tests only apply this [via config and dep injection](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/main/tests/test_integration.py#L82-L87) so we should be safe 👍

**Comment by ranchodeluxe** [comment]
already folded into `@main` and working so closing
