### ISSUE TITLE
Consolidating release notes

### ISSUE THREAD

**Issue by abarciauskas-bgse** [pangeo-forge/pangeo-forge-recipes#705]
In looking to document how we do releases, I noticed that release notes are located both https://github.com/pangeo-forge/pangeo-forge-recipes/releases and https://pangeo-forge.readthedocs.io/en/latest/release_notes.html.

Most releases, prior to 0.10.4, with the exception of 0.9.2, link to https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/development/release_notes.html which is a broken link and is probably meant to point to https://pangeo-forge.readthedocs.io/en/latest/release_notes.html.

I would propose we move all release notes from https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/development/release_notes.html to https://github.com/pangeo-forge/pangeo-forge-recipes/releases and update the docs website accordingly (revise https://pangeo-forge.readthedocs.io/en/latest/contributing.html#releasing and remove https://pangeo-forge.readthedocs.io/en/latest/release_notes.html) so that all the release notes are in one place (and that is the same as where the auto-generated release notes can be created).

I am happy to do it if this plan sounds ok to @cisaacstern @ranchodeluxe @jbusecke

**Comment by norlandrhagen** [comment]
Seems like a great call @abarciauskas-bgse 1

**Comment by cisaacstern** [comment]
@abarciauskas-bgse this is genius! I was literally just thinking this week, "uh, release notes really are too toilsome, and it makes releasing way harder than it needs to be." This is a perfect solution! Would be awesome if you could do this, and a really boost to our iteration speed and ergonomics!

**Comment by cisaacstern** [comment]
closed by #706
