### ISSUE TITLE
Pre-compute sequence-dim coordinates in prepare_target

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#90]
We currently build up the sequence-dim coordinate (usually `time`) one chunk at a time. As noted by @shoyer in https://github.com/pangeo-forge/pangeo-forge/pull/86#issuecomment-811501781, it may often be possible to pre-populate this information and write the entire chunk at once inside `prepare_target`.

An alternative would be to consolidate the sequence_dim chunks at the end, in `finalize_target`. That would likely be more robust to corner cases.

**Comment by martindurant** [comment]
Is there a possibility of a post-process step to consolidate coordinate data? It could depend on some heuristic for chunk-size.

**Comment by rabernat** [comment]
That is what `finalize_target` is for.

https://github.com/pangeo-forge/pangeo-forge/blob/3314162568f7d8fe3d6f06627b936cee55d99c9c/pangeo_forge/recipe.py#L316-L324

We could easily add consolidation of chunks to that step.

**Comment by rabernat** [comment]
The post-write consolidation of coordinates has been implemented in #210. I'm going to close this for now. Thanks for the suggestions everyone.
